#!/usr/bin/env python3
"""Generate per-language data files from the single source of truth data/name_cn.json.

Usage:
    uv run scripts/gen.py            # regenerate all, compare against existing
    uv run scripts/gen.py --write    # regenerate and write to disk
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "name_cn.json"
OUT = {
    "python": ROOT / "python" / "opencc_cn_name" / "_data.py",
    "js": ROOT / "js" / "data_gen.js",
}


def esc(c: str) -> str:
    if c in ("'", "\\"):
        return "'" + c
    return c


def py_table(d: dict) -> str:
    jp2t = ", ".join("'" + esc(c) + "'" for c in d["jp2t_exclude"])
    t2s = ", ".join("'" + esc(c) + "'" for c in d["t2s_exclude"])
    vm = ", ".join(f"'{esc(k)}': '{esc(v)}'" for k, v in d["variant_map"].items())
    return f"""# Generated by scripts/gen.py — do not edit.
# Source: {DATA.relative_to(ROOT)}

JP2T_EXCLUDE = frozenset({{{jp2t}}})
T2S_EXCLUDE = frozenset({{{t2s}}})
# str.maketrans keeps int codepoint keys, which str.translate requires
VARIANT_MAP = str.maketrans({{
    {vm},
}})
"""


def js_table(d: dict) -> str:
    jp2t = ", ".join("'" + c + "'" for c in d["jp2t_exclude"])
    t2s = ", ".join("'" + c + "'" for c in d["t2s_exclude"])
    vm = ", ".join(f"'{k}': '{v}'" for k, v in d["variant_map"].items())
    return f"""// Generated by scripts/gen.py — do not edit.
// Source: {DATA.relative_to(ROOT)}

export const JP2T_EXCLUDE = new Set([{jp2t}]);

export const T2S_EXCLUDE = new Set([{t2s}]);

export const VARIANT_MAP = {{ {vm} }};
"""


def main() -> None:
    data = json.loads(DATA.read_text(encoding="utf-8"))
    writers = {"python": py_table, "js": js_table}
    write = "--write" in sys.argv
    changed = []
    for lang, fn in writers.items():
        content = fn(data)
        path = OUT[lang]
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        if write:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
        else:
            changed.append(path.relative_to(ROOT).as_posix())
    if changed:
        print(f"drift detected (run with --write to sync): {', '.join(changed)}")
        sys.exit(1)


if __name__ == "__main__":
    main()
